Object.extend=function(a,b){for(var c in b)a[c]=b[c];return a};window.lib=window.lib||{};if(!lib.SITE_DOMAIN){var getDomain=function(){var a=window.location.hostname.split("."),a=a.slice(a.length-2);return a.join(".")};lib.SITE_DOMAIN=getDomain()}lib.action=lib.action||{};
lib.action.Qa=function(){this.init=function(a){var b=this;try{var c=navigator.userAgent.toLowerCase();this.par={};this.pars=[];this.custom={};this.filter=[];this.time=0;this.w=window;this.l=window.location;this.d=window.document;this.urlMap={rdm:"rdm",qtcurl:"qtcurl",rfr:"rfr",lrfr:"lrfr",jsuid:"jsuid",qtsid:"qtsid",ppuid:"ppuid",platform:"platform",weid:"weid",flshuid:"flshuid",fcode:"fcode",ffcode:"ffcode",coop:"coop"};this.cookieMap={flshuid:"QC005",jsuid:"QC006",lrfr:"QC007",qtsid:"QC008",QY_FC:"QC009",
QY_FFC:"QC014",gaflag:"QC011"};a=a||{};this.times=a.times||5;this.timeouts=a.timeouts||1E3;this.url=a.url||window.location.protocol+"//msg.iqiyi.com/jspb.gif";this.url+="?";this.flag=a.flag||"QC010";this.callback=a.callback||function(){};typeof a.urlMap=="object"&&Object.extend(this.urlMap,a.urlMap);typeof a.cookieMap=="object"&&Object.extend(this.cookieMap,a.cookieMap);typeof a.custom=="object"&&Object.extend(this.custom,a.custom);if(a.filter instanceof Array)this.filter=a.filter;var d=this.urlMap;
this.setGa();this.par[d.rdm]=this.rand();this.par[d.qtcurl]=this.u(this.l.href);this.par[d.rfr]=this.u(this.d.referrer);this.par[d.lrfr]=this.getLrfr();this.par[d.jsuid]=this.getJsuid();this.par[d.qtsid]=this.getQtsid();this.par[d.ppuid]=this.getUserInfoUid();this.par[d.platform]=/ipad/.test(c)?21:/iphone os/.test(c)?31:11;this.par[d.fcode]=this.getFc();this.par[d.ffcode]=this.getFfc();this.par[d.coop]=this.getCoop();this.par.mhf="1";Object.extend(this.par,this.custom);setTimeout(function(){var a=
navigator.userAgent.toLowerCase(),a=/ipad/.test(a)||/iphone os/.test(a)||/lepad_hls/.test(a);lib.qa_postServerUID&&b.w.webEventID||b.time>=b.times||a?(b.par[d.weid]=b.w.webEventID||b.localEventId(),b.par[d.flshuid]=b.setFlashId(lib.qa_postServerUID||""),b.post(),a=!0):(b.time+=1,a=!1);a===!1&&setTimeout(arguments.callee,b.timeouts)},0)}catch(e){}};this.getUserInfoUid=function(){try{var a=this.cookieGet("P00002");a&&(a=a==window.JSON?window.JSON.parse(a):eval("("+a+")"));return a&&a.uid?a.uid:""}catch(b){return""}};
this.localEventId=function(){try{for(var a=(new Date).getTime().toString(),b=String(Math.floor(999999999*Math.random()));b.length<9;)b="0"+b;this.w.webEventID=a.substr(a.length-10,10)+b;return this.w.webEventID}catch(c){return""}};this.u=function(a){try{var b=encodeURIComponent;return b instanceof Function?b(a):escape(a)}catch(c){return""}};this.hash=function(a){try{var b=1,c=0;if(a)for(var b=0,d=a.length-1;d>=0;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=c!==0?b^c>>21:b;return b}catch(e){return""}};
this.rand=function(a){try{var b=[];if(isNaN(a))b.push(Math.round(Math.random()*2147483647));else for(var c=0;c<a;c++)b.push(Math.round(Math.random()*2147483647).toString(36));return b.join("")}catch(d){return""}};this.cookieGet=function(a){try{var a=a.replace(/([\.\[\]\$])/g,"\\$1"),b=(document.cookie+";").match(RegExp(a+"=([^;]*)?;","i"));return b?b.length>1&&b[1]=="deleted"?"":decodeURIComponent(b[1])||"":""}catch(c){return""}};this.cookieSet=function(a,b,c,d,e,h){try{var f=[];f.push(a+"="+encodeURIComponent(b));
if(c){var g=new Date,i=g.getTime()+c*36E5;g.setTime(i);f.push("expires="+g.toGMTString())}d&&f.push("path="+d);e&&f.push("domain="+e);h&&f.push(h);document.cookie=f.join(";")}catch(j){return""}};this.getJsuid=function(){try{var a,b=this.cookieMap.jsuid;a=this.cookieGet(b);if(!a||!isNaN(a))a=this.rand(4);this.cookieSet(b,a,8760,"/",lib.SITE_DOMAIN);return a}catch(c){return""}};this.getQtsid=function(){try{var a,b=this.cookieMap.qtsid;a=this.cookieGet(b);if(this.cookieGet(this.flag))return a;if(/^\d{10}\.\d{10}\.\d{10}\.\d+$/.test(a))a=
a.split("."),a[1]=a[2],a[2]=parseInt(new Date/1E3,10).toString(),a[3]=parseInt(a[3],10)+1;else{var c=parseInt(new Date/1E3,10).toString();a=[c,c,c,"1"]}this.cookieSet(b,a.join("."),8760,"/",lib.SITE_DOMAIN);return a}catch(d){return""}};this.getLrfr=function(){try{var a,b=this.cookieMap.lrfr,c=this.d.referrer.match(/http[s]?:\/\/([^\/]*)/),c=c?c[1]:"";a=this.cookieGet(b);a=a=="undefined"?"":a;var d=this.l.hostname;a?this.d.referrer?c!==d&&c.indexOf("iqiyi.com")===-1&&(a=this.u(this.d.referrer)):a=
"DIRECT":a=this.d.referrer?this.u(this.d.referrer):"DIRECT";this.cookieSet(b,a,0,"/",lib.SITE_DOMAIN);return a}catch(e){return""}};this.setFlashId=function(a){var b=this.cookieMap.flshuid;key=this.cookieGet(b);a&&a!=key&&this.cookieSet(b,a,8760,"/",lib.SITE_DOMAIN);return a};this.getFc=function(){try{var a=this.l.search.match(/[\?&]fc=([^&]*)(&|$)/i),b=this.cookieMap.QY_FC,c=this.cookieGet(b);if(c=="b22dab601821a896")return c;if(a)a=a[1],this.cookieSet(b,a,0,"/",lib.SITE_DOMAIN);else if(a=this.cookieGet(b),
!a||a=="undefined")a="";return a}catch(d){return""}};this.getFfc=function(){try{var a=this.l.search.match(/[\?&]ffc=([^&]*)(&|$)/i),b=this.cookieMap.QY_FFC;if(a)a=a[1],this.cookieSet(b,a,0,"/",lib.SITE_DOMAIN);else if(a=this.cookieGet(b),!a||a=="undefined")a="";return a}catch(c){return""}};this.getCoop=function(){var a="",b;if(this.l.host.split(".")[0]=="mini")(b=(b=lib.$url(this.l.href,"app"))&&b.app||"")&&(a="coop_"+b.replace("bdbrowser","bdexplorer"));else if(this.w.INFO&&this.w.INFO.flashVars&&
this.w.INFO.flashVars.coop)a=this.w.INFO.flashVars.coop;return a};this.setGa=function(){var a=this.cookieMap.gaflag;this.cookieGet(a)||this.cookieSet(a,Math.ceil(Math.random()*2E3),8760,"/",lib.SITE_DOMAIN)};this.post=function(){try{this.pars=[];var a,b=this.filter.length,c;if(b===0)for(a in this.par)this.pars.push([a,this.par[a]].join("="));else for(a=0;a<b;a++)c=this.filter[a],this.pars.push([c,this.par[c]].join("="));this.pars=this.pars.join("&");window.jsQa=new Image(1,1);jsQa.src=this.url+this.pars;
this.cookieSet(this.flag,this.hash(this.pars),0,"/",lib.SITE_DOMAIN);this.callback()}catch(d){return""}}};(function(){var a=new lib.action.Qa;try{a.init({url:window.location.protocol+"//msg.iqiyi.com/jpb.gif"})}catch(b){}})();
(function(){var a=new lib.action.Qa,b=a.cookieGet("QC001")=="1",c=a.cookieGet("QC005"),d;if(!b&&c&&window.location.protocol!="https:"){a.cookieSet("QC001","1",24,"/",lib.SITE_DOMAIN);var a={qiyi_cookie:c},c={sid:c,p:"iqiyi"},b=[],e="BD_QIYI_LOG_"+(new Date).getTime(),e=window[e]=new Image;b.push("pid=324");for(d in a)b.push(d+"="+encodeURIComponent(a[d]));e.src="http://nsclick.baidu.com/v.gif?"+b.join("&")+"&t="+(new Date).getTime();a=[];b="BD_QIYI_LOG_"+(new Date).getTime();b=window[b]=new Image;
for(d in c)a.push(d+"="+encodeURIComponent(c[d]));b.src="http://cpro.baidu.com/cpro/ui/html/sync.htm?"+a.join("&")+"&t="+(new Date).getTime()}})();
(function(){if(document.cookie.match(/QC011=271/)){window._gaq=window._gaq||[];_gaq.push(["_setAccount","UA-33639254-1"]);_gaq.push(["_setDomainName","iqiyi.com"]);_gaq.push(["_trackPageview"]);var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}})();
(function(){var a=function(a){var a=a||window.event,a={re:Math.max(document.documentElement&&document.documentElement.scrollWidth||document.body.scrollWidth,document.documentElement&&document.documentElement.clientWidth||document.body.clientWidth)+"*"+Math.max(document.documentElement&&document.documentElement.scrollHeight||document.body.scrollHeight,document.documentElement&&document.documentElement.clientHeight||document.body.clientHeight),clkx:a.clientX+(document.documentElement&&document.documentElement.scrollLeft||
document.body.scrollLeft),clky:a.clientY+(document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop)},b="http://msg.iqiyi.com/b?t=20&pf=1&p=10&p1=101",a=a||{};b+=b.indexOf("?")==-1?"?":"&";a._=+new Date;for(var e in a)a.hasOwnProperty(e)&&(b+=encodeURIComponent(e)+"="+encodeURIComponent(a[e])+"&");b[b.length-1]==="&"&&(b=b.slice(0,-1));(new Image).src=b},b=window.document.getElementsByTagName("body")[0];b.addEventListener?b.addEventListener("click",a,!0):b.attachEvent("onclick",
a)})();
