<?php
//include "./info/youku.php";

$r='12';
if(isset($_GET["r"])){
    $r=$_GET["r"];
}else{
$r="not set";
}
//测试


echo '<ROOT>
    <RVIDEO>
        <RV>
           <title>'.$r.'_1</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA1NzE2/v.swf
            </url>
            <l>3</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117044131_4718.jpg</pic>
            <vid>140</vid>
        </RV>
        <RV>
           <title>'.$r.'_2</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA1NTYw/v.swf
            </url>
            <l>0</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117044338_6316.jpg</pic>
            <vid>141</vid>
        </RV>
        <RV>
         <title>'.$r.'_3</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA1NDA4/v.swf
            </url>
            <l>3</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117051602_7079.jpg</pic>
            <vid>142</vid>
        </RV>
        <RV>
         <title>'.$r.'_4</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA2ODUy/v.swf
            </url>
            <l>0</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117044704_9399.jpg</pic>
            <vid>143</vid>
        </RV>
        <RV>
           <title>'.$r.'_5</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA2OTg0/v.swf
            </url>
            <l>2</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117045221_6820.jpg</pic>
            <vid>144</vid>
        </RV>
        <RV>
           <title>'.$r.'_6</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA3MDcy/v.swf
            </url>
            <l>0</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117045618_4390.jpg</pic>
            <vid>145</vid>
        </RV>
        <RV>
          <title>'.$r.'_7</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA3MTc2/v.swf
            </url>
            <l>0</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117045849_8316.jpg</pic>
            <vid>146</vid>
        </RV>
        <RV>
          <title>'.$r.'_8</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA3MzI0/v.swf
            </url>
            <l>2</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117050040_5058.jpg</pic>
            <vid>147</vid>
        </RV>
        <RV>
            <title>'.$r.'_9</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA3NDk2/v.swf
            </url>
            <l>0</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117050208_3212.jpg</pic>
            <vid>148</vid>
        </RV>
        <RV>
           <title>'.$r.'_10</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA3NjE2/v.swf
            </url>
            <l>2</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117050313_4035.jpg</pic>
            <vid>149</vid>
        </RV>
        <RV>
            <title>'.$r.'_11</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA3Nzky/v.swf
            </url>
            <l>2</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117050423_6139.jpg</pic>
            <vid>150</vid>
        </RV>
        <RV>
          <title>'.$r.'_12</title>
            <url>
                http://localhost/player/ckplayer/video.php?url=http://player.youku.com/player.php/sid/XMTg5OTA3OTYw/v.swf
            </url>
            <l>2</l>
            <pic>http://www.7evs.com/attachments/video/201311/20131117050530_5378.jpg</pic>
            <vid>151</vid>
        </RV>
    </RVIDEO>
</ROOT>';




?>